### ISSUE TITLE
Support Ruby 2.3 on Windows

### ISSUE THREAD

**Issue by scivola** [codahale/bcrypt-ruby#139] opened 2016-04-07 00:55 UTC
bcrypt (3.1.11 x86-mingw32) does not contain binary for Ruby 2.3.

Now Windows users can use Ruby 2.3.
http://rubyinstaller.org/downloads/

**Comment by Startouf** [comment] 2016-04-15 23:58
So basically the same problem as in https://github.com/codahale/bcrypt-ruby/issues/128 ?

**Comment by scivola** [comment] 2016-04-16 11:19
Yes, it is essentially same.

**Comment by Startouf** [comment] 2016-06-06 23:47
What should be done to generate a version for Ruby 2.3 (if it is possible). This is the only step that prevents me from migrating to Ruby 2.3.

**Comment by vais** [comment] 2016-07-12 07:59
@Startouf the following worked for me (with [DevKit](http://rubyinstaller.org/add-ons/devkit/)):
```
C:\Users\Administrator>ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]

C:\Users\Administrator>gem list bcrypt

*** LOCAL GEMS ***

bcrypt (3.1.11 x64-mingw32)

C:\Users\Administrator>gem uninstall bcrypt
Successfully uninstalled bcrypt-3.1.11-x64-mingw32

C:\Users\Administrator>gem list bcrypt

*** LOCAL GEMS ***

C:\Users\Administrator>gem install bcrypt --platform=ruby
Fetching: bcrypt-3.1.11.gem (100%)
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
Successfully installed bcrypt-3.1.11
Parsing documentation for bcrypt-3.1.11
Installing ri documentation for bcrypt-3.1.11
Done installing documentation for bcrypt after 1 seconds
1 gem installed

C:\Users\Administrator>gem list bcrypt

*** LOCAL GEMS ***

bcrypt (3.1.11)
```
:beers:

**Comment by larskanis** [comment] 2016-07-28 15:13
#117 fixes this issue. Alternatively use the workaround with `gem inst --platform=ruby` .

**Comment by caleuanhopkins** [comment] 2016-09-14 12:58
Funnily enough, the solution (or work around, whatever you want to call it) seems to fix this issue also: [https://github.com/codahale/bcrypt-ruby/issues/128#issuecomment-190107035](https://github.com/codahale/bcrypt-ruby/issues/128#issuecomment-190107035)

**Comment by sorelyss** [comment] 2016-09-23 17:56
It works!!! thanks 👍

**Comment by amreos** [comment] 2016-10-05 00:00
Dear @vais 
Thank you 
this worked for ruby 2.3 32bit version on x64 win 7 if that make any sense
i had to delete any other bcrypt folder in this bath
C:\Ruby23\lib\ruby\gems\2.3.0\gems
thanks again

**Comment by jostster** [comment] 2016-11-04 00:48
This there a perm fix for this inside the Gemfile? I hate having to install new gems with `bundle install` then uninstall bcrypt manually then manually reinstall it with the platform=ruby.

**Comment by karensg** [comment] 2016-12-23 13:27
This would be really great!

**Comment by enneid** [comment] 2017-03-10 12:07
Is it this problem will be perm fixed in any time? or we have to wait for ruby 2.4?

**Comment by bchellingworth** [comment] 2017-04-22 02:44
Is this issue ever going to get a perm fix, the workaround is painful everytime.

**Comment by sdik** [comment] 2017-05-02 01:27
gem install bcrypt --platform=ruby
resolveu..

**Comment by mSafdarAli** [comment] 2017-07-12 03:44
@vais thank you so much. it solved my problem. :+1:

**Comment by johnnyshields** [comment] 2018-01-18 15:41
This is a dupe of #149 and can be closed (we only need one ticket for it)

**Comment by tjschuck** [comment] 2018-05-15 19:34
I have just pushed version 3.1.12.rc1 to RubyGems.org which should solve this problem.

Can someone please confirm that `gem install bcrypt --prerelease` now works on Fedora 28?  If so, I'll push out the final version.

**Comment by tjschuck** [comment] 2018-05-16 20:08
Version 3.1.12 of the bcrypt gem, which should fix this issue, was just pushed to RubyGems.

You should now be able to `gem install bcrypt` on Windows with none of the above workarounds.

Thanks, everyone!

**Closed by tjschuck** 2018-05-16 20:08 UTC
